sonarr:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        thehomelab.tech/dnsprovider: carsonanderson-net-aws
        thehomelab.tech/ip-address: internal
        thehomelab.tech/iplookup: aws
      hosts:
        - host: sonarr.carsonanderson.net
          ## Configure the paths for the host
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: sonarr-tls
          hosts:
            - sonarr.carsonanderson.net
  persistence:
    config:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteOnce
    media:
      enabled: true
      mountPath: /media
      existingClaim: plex-media
