nzbget:
  securityContext:
    fsGroup: 100
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        thehomelab.tech/dnsprovider: carsonisawesome-com-aws
        thehomelab.tech/ip-address: internal
        thehomelab.tech/iplookup: aws
      hosts:
        - host: nzbget.carsonanderson.net
          ## Configure the paths for the host
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: nzbget-tls
          hosts:
            - nzbget.carsonanderson.net
  persistence:
    config:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteOnce
    media:
      enabled: true
      mountPath: /media
      existingClaim: plex-media
    downloads:
      enabled: true
      mountPath: /downloads
      size: 150Gi
      accessMode: ReadWriteOnce
